### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by ltennstedt** [zwaldowski/git-commit-action#1]
Using git-commit-action@v1 throws the error `Error: Cannot find module '@actions/core'`.

[job.log](https://github.com/zwaldowski/git-commit-action/files/4026197/job.log)

**Comment by zwaldowski** [comment]
Looks like I screwed up the tag. [It's passing now.](https://github.com/zwaldowski/git-commit-action/actions). Please reopen the issue if there's still a problem. Thank you!
